### ISSUE TITLE
Add a note for alternate schedules

### ISSUE THREAD

**Issue by anematode** [Orbiit/ugwisha#25]
Either always, or only when there are displayed alternate schedules: have a note with the text "*alternate schedule" or the like underneath the schedule display.

**Comment by anematode** [comment]
![Screen Shot 2019-05-31 at 21 23 22](https://user-images.githubusercontent.com/26530804/58743641-58634f00-83ea-11e9-8dde-5070e1f50def.png)

**Comment by SheepTester** [comment]
it ruins the design and I'm ~~quite~~ ~~somewhat~~ meagerly sure people can figure it out themselves (also it already says so per day)
